# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "zJhfSRfbaQqd1i0wuSwOCIN+RffgpBW1NSV4KAD8NnCcpZyxnufbcAOsaSnfmLYRRzhtV+c6YGL3Fk/u1+RVgmVIUVE+xU2LAW/h6XjlQm7zp0vZ5lFszg8J1pJK96x+1vHeN3Y9Y+23Q0+b2vAzZIB5RLjUCZQ8cf6hksT7kxh1a/k7h7UbZBT+J8jTpG/MSO2PErbexaV5CP4V4ke+aaEgej0NfjryurKBjOxFfHXrcN9hf1546CfMcp45aSIV3KQa6bQXdJoIGUo5Ga3550S2ZsBBbkXY7sjOyvWmzZpgVrW9OPvDuOVY1diYz/A2hNlwKls6PyYbknKkH/qbLoRU6k1bb3PMFSKZA5mjtA+d0hXPTngrL3la0qu+7D2qpNtt9aj8RPicHioRAu4TL9Rru+CjJAgJCTvXebCvfKtgnPoaSDZb+amGeePXw6V6IjZLAMEa4lkUG5h4xpUy3+s2pTSpMFl2xQZXGIGdGtfDBQZncyuvUlVLtPyA+uAB5/+heijg5q9PtNR0j2CThLZ/cHH3Yor87v8+/vdtdC8pl0BcJo08ddoNfC9RiYJmrXAA4MHnrqoUlmw6hVa0ctnr3pRjyKSRXzTqgLZMrTnjETOTtcss2COeCkhotsng69no843eK+LrUUPmB3FYgr7RzdQdpnkZrbxcsGbZdpw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
